# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 10 Apr 2013 22:43:50 +0000
*               @ALL          0
*               @user         8
