<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: matias
 * Date: Wed, 10 Apr 2013 19:57:59 -0300
 */

$conf['title'] = 'Organizacion';
$conf['lang'] = 'es';
$conf['template'] = 'sidebar';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
